sudo: required

services:
  - docker
  - docker-compose

global:
  - DOCKER_COMPOSE_VERSION=1.19.0

env:
  matrix:
    - PLATFORM_PROFILE=multisite_drupal_standard
      THEME_DEFAULT=ec_resp
      BEHAT_PROFILE=standard_ec_resp
    - PLATFORM_PROFILE=multisite_drupal_standard
      THEME_DEFAULT=ec_europa
      BEHAT_PROFILE=default
    - PLATFORM_PROFILE=multisite_drupal_communities
      THEME_DEFAULT=ec_resp
      BEHAT_PROFILE=communities_ec_resp
    - PLATFORM_PROFILE=multisite_drupal_communities
      THEME_DEFAULT=ec_europa
      BEHAT_PROFILE=communities

before_install:
  - sudo /etc/init.d/mysql stop
  - git clone https://github.com/ec-europa/platform-dev.git
  - cp build.properties.local platform-dev/
  - docker-compose build
  - docker-compose up --no-start
  - docker-compose start

install:
  - docker-compose exec web composer install
  - docker-compose exec web ./bin/phing build-platform-dev -D'platform.profile.name'=$PLATFORM_PROFILE
  - docker-compose exec web ./bin/phing install-platform -D'platform.profile.name'=$PLATFORM_PROFILE -D'platform.site.theme_default'=$THEME_DEFAULT

script:
  - docker-compose exec web ./bin/phpcs
  - docker-compose exec web ./bin/phpunit -c tests/phpunit.xml
  - travis_wait 60 docker-compose exec web ./bin/behat -c tests/behat.yml -p $BEHAT_PROFILE

notifications:
 email: false
