sudo: required

services:
  - docker
  - docker-compose

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.19.0
  matrix:
    - PLATFORM_VERSION=master
    - PLATFORM_VERSION=release-2.5

before_install:
  - sudo /etc/init.d/mysql stop
  - git clone -b $PLATFORM_VERSION https://github.com/ec-europa/platform-dev.git
  - git clone https://github.com/ec-europa/atomium.git
  - git clone https://github.com/ec-europa/ec_resp.git
  - git clone https://github.com/ec-europa/ec_europa.git
  - cp build.properties.local platform-dev/
  - docker-compose build
  - docker-compose up --no-start
  - docker-compose start

install:
  - docker-compose exec web composer install
  - docker-compose exec web ./bin/phing build-platform-dev
  - docker-compose exec web ./bin/phing install-platform

before_script:
  - sudo rm -rf platform-dev/profiles/multisite_drupal_standard/themes/*
  - sudo ln -s ../../../../atomium ./platform-dev/profiles/multisite_drupal_standard/themes/
  - sudo ln -s ../../../../ec_resp ./platform-dev/profiles/multisite_drupal_standard/themes/
  - sudo ln -s ../../../../ec_europa ./platform-dev/profiles/multisite_drupal_standard/themes/

script:
  - docker-compose exec web ./bin/phpcs
  - docker-compose exec web ./bin/phpunit -c tests/phpunit.xml
  - docker-compose exec web ./bin/behat -c tests/behat.yml

notifications:
 email: false
