version: '2'
services:
  web:
    image: fpfis/php56-dev
    working_dir: /var/www/html
    environment:
      - DOCUMENT_ROOT=/var/www/html
      - BLACKFIRE_CLIENT_ID
      - BLACKFIRE_CLIENT_TOKEN
    volumes:
      - ./platform-dev:/var/www/html
      - ./ec_resp:/var/www/ec_resp
      - ./atomium:/var/www/atomium
      - ./ec_europa:/var/www/ec_europa
    ports:
      - ${HTTP_PORT}:8080
    depends_on:
      - mysql
  blackfire:
    image: blackfire/blackfire
    environment:
      - BLACKFIRE_SERVER_ID
      - BLACKFIRE_SERVER_TOKEN
  mysql:
    image: fpfis/mysql56
    volumes:
      - my-datavolume:/var/lib/mysql
  selhub:
    image: selenium/hub
    ports:
      - 4444:4444
  nodeff:
    image: selenium/node-firefox-debug
    ports:
      - 5900
    links:
      - selhub:hub
  nodechrome:
    image: selenium/node-chrome-debug
    ports:
      - 5900
    links:
      - selhub:hub
volumes:
  my-datavolume:
