version: '2'
services:

  web:
    image: fpfis/php56-dev
    working_dir: /var/www/html
    environment:
      - DOCUMENT_ROOT=/var/www/html
      - BLACKFIRE_CLIENT_ID
      - BLACKFIRE_CLIENT_TOKEN
    volumes:
      - ./platform-dev:/var/www/html
      - ./ec_resp:/var/www/ec_resp
      - ./atomium:/var/www/atomium
      - ./ec_europa:/var/www/ec_europa
    ports:
      - ${HTTP_PORT}:8080
    links:
      - phantomjs
      - selenium-chrome
      - selenium-firefox
    depends_on:
      - mysql

  mysql:
    image: fpfis/mysql56
    volumes:
      - my-datavolume:/var/lib/mysql

  blackfire:
    image: blackfire/blackfire
    environment:
      - BLACKFIRE_SERVER_ID
      - BLACKFIRE_SERVER_TOKEN

  phantomjs:
    image: wernight/phantomjs
    container_name: phantomjs
    restart: always
    ports:
      - "4442:8910"
    command: "phantomjs --webdriver=8910 --ignore-ssl-errors=true --ssl-protocol=any"

  selenium-chrome:
    image: selenium/standalone-chrome
    container_name: selenium-chrome
    restart: always
    ports:
      - "4440:4444"

  selenium-firefox:
    image: selenium/standalone-firefox
    container_name: selenium-firefox
    restart: always
    ports:
      - "4444:4444"

volumes:
  my-datavolume:


